import InfinitaryCombinatorics.AlmostContainment
import R0.Main

namespace InfinitaryCombinatorics
open Set
universe u
variable {X : Type u}

/-- AD permits finite families; each member must still be infinite. -/
def ADFamily (A : Set (Set X)) : Prop :=
  (∀ a ∈ A, a.Infinite) ∧ ∀ a ∈ A, ∀ b ∈ A, a ≠ b → (a ∩ b).Finite

theorem infinite_ad_iff (A : Set (Set X)) :
    R0.AlmostDisjoint A ↔ A.Infinite ∧ ADFamily A := Iff.rfl

theorem ADFamily.mono {A B : Set (Set X)} (hB : ADFamily B) (hAB : A ⊆ B) :
    ADFamily A :=
  ⟨fun a ha => hB.1 a (hAB ha), fun a ha b hb => hB.2 a (hAB ha) b (hAB hb)⟩

/-- The ideal generated by the family together with all finite sets. -/
def InIdeal (A : Set (Set X)) (x : Set X) : Prop :=
  ∃ F : Set (Set X), F.Finite ∧ F ⊆ A ∧ AlmostSubset x (⋃ a ∈ F, a)

theorem inIdeal_of_finite (A : Set (Set X)) {x : Set X} (hx : x.Finite) :
    InIdeal A x := by
  refine ⟨∅, finite_empty, empty_subset _, ?_⟩
  simpa [AlmostSubset] using hx

theorem inIdeal_of_mem {A : Set (Set X)} {a : Set X} (ha : a ∈ A) : InIdeal A a := by
  refine ⟨{a}, finite_singleton a, singleton_subset_iff.mpr ha, ?_⟩
  simp [AlmostSubset]

theorem InIdeal.mono {A : Set (Set X)} {x y : Set X}
    (hy : InIdeal A y) (hxy : x ⊆ y) : InIdeal A x := by
  obtain ⟨F, hF, hFA, hyF⟩ := hy
  exact ⟨F, hF, hFA, (almostSubset_of_subset hxy).trans hyF⟩

theorem InIdeal.union {A : Set (Set X)} {x y : Set X}
    (hx : InIdeal A x) (hy : InIdeal A y) : InIdeal A (x ∪ y) := by
  obtain ⟨F, hF, hFA, hxF⟩ := hx
  obtain ⟨G, hG, hGA, hyG⟩ := hy
  refine ⟨F ∪ G, hF.union hG, union_subset hFA hGA, ?_⟩
  apply (hxF.union hyG).subset
  rintro z ⟨hz, hnot⟩
  rcases hz with hz | hz
  · exact Or.inl ⟨hz, fun h => hnot (by
      obtain ⟨a, ha, hza⟩ := mem_iUnion₂.mp h
      exact mem_iUnion₂.mpr ⟨a, Or.inl ha, hza⟩)⟩
  · exact Or.inr ⟨hz, fun h => hnot (by
      obtain ⟨a, ha, hza⟩ := mem_iUnion₂.mp h
      exact mem_iUnion₂.mpr ⟨a, Or.inr ha, hza⟩)⟩

/-- Infinite-family convention for MAD, excluding finite partitions of the base. -/
def MAD (A : Set (Set X)) : Prop :=
  R0.AlmostDisjoint A ∧ ∀ x : Set X, x.Infinite → ∃ a ∈ A, (x ∩ a).Infinite

theorem mad_iff_maximal (A : Set (Set X)) : MAD A ↔
    R0.AlmostDisjoint A ∧ ∀ B, ADFamily B → A ⊆ B → B = A := by
  constructor
  · rintro ⟨hA, hm⟩
    refine ⟨hA, ?_⟩
    intro B hB hAB
    apply Subset.antisymm ?_ hAB
    intro b hb
    obtain ⟨a, ha, hba⟩ := hm b (hB.1 b hb)
    by_contra hnot
    exact hba (hB.2 b hb a (hAB ha) (fun h => hnot (h ▸ ha)))
  · rintro ⟨hA, hm⟩
    refine ⟨hA, ?_⟩
    intro x hx
    by_contra hn
    have hfin : ∀ a ∈ A, (x ∩ a).Finite := by
      intro a ha
      exact not_infinite.mp (fun h => hn ⟨a, ha, h⟩)
    have hi : ADFamily (insert x A) := by
      constructor
      · intro a ha
        rcases mem_insert_iff.mp ha with rfl | ha
        · exact hx
        · exact hA.2.1 a ha
      · intro a ha b hb hab
        by_cases hax : a = x
        · subst a
          have hbA : b ∈ A := (mem_insert_iff.mp hb).resolve_left (Ne.symm hab)
          exact hfin b hbA
        · have haA : a ∈ A := (mem_insert_iff.mp ha).resolve_left hax
          by_cases hbx : b = x
          · subst b
            simpa [inter_comm] using hfin a haA
          · have hbA : b ∈ A := (mem_insert_iff.mp hb).resolve_left hbx
            exact hA.2.2 a haA b hbA hab
    have hxA : x ∈ A := hm (insert x A) hi (subset_insert x A) ▸ mem_insert x A
    exact hx (by simpa using hfin x hxA)

def NowhereMAD (A : Set (Set X)) : Prop :=
  ADFamily A ∧ ∀ x : Set X, ¬ InIdeal A x →
    ∃ y ⊆ x, y.Infinite ∧ ∀ a ∈ A, (y ∩ a).Finite

/-- Infinitely many AD members prevent a finite union from covering the base modulo finite. -/
theorem ideal_proper_of_infinite_ad {A : Set (Set X)} (hA : R0.AlmostDisjoint A) :
    ¬ InIdeal A univ := by
  rintro ⟨F, hF, hFA, hcover⟩
  obtain ⟨a, haA, haF⟩ := (hA.1.diff hF).nonempty
  have hbad : (⋃ b ∈ F, a ∩ b).Finite := hF.biUnion fun b hb =>
    hA.2.2 a haA b (hFA hb) (fun hab => haF (hab.symm ▸ hb))
  apply hA.2.1 a haA
  apply (hcover.union hbad).subset
  intro x hx
  by_cases hxu : x ∈ ⋃ b ∈ F, b
  · obtain ⟨b, hb, hxb⟩ := mem_iUnion₂.mp hxu
    exact Or.inr (mem_iUnion₂.mpr ⟨b, hb, hx, hxb⟩)
  · exact Or.inl ⟨mem_univ x, hxu⟩

theorem nowhereMAD_not_MAD {A : Set (Set X)} (hA : R0.AlmostDisjoint A)
    (hn : NowhereMAD A) : ¬ MAD A := by
  intro hm
  obtain ⟨y, _, hy, hya⟩ := hn.2 univ (ideal_proper_of_infinite_ad hA)
  obtain ⟨a, ha, hyaInf⟩ := hm.2 y hy
  exact hyaInf (hya a ha)

end InfinitaryCombinatorics



