name = "fiMadModels"
version = "0.1.0"
defaultTargets = ["FIMADModels"]

[[lean_lib]]
name = "Formalizations"
srcDir = ".."
roots = ["Formalizations.FIMAD.InternalSemantics", "Formalizations.FIMAD.SetTheorySentence", "Formalizations.FIMAD.CheckedZFC", "Formalizations.FIMAD.PosetRegular", "Formalizations.FIMAD.BooleanEnumeration", "Formalizations.FIMAD.UnboundedSyntax"]
globs = ["Formalizations.FIMAD.InternalSemantics", "Formalizations.FIMAD.SetTheorySentence", "Formalizations.FIMAD.CheckedZFC", "Formalizations.FIMAD.PosetRegular", "Formalizations.FIMAD.BooleanEnumeration", "Formalizations.FIMAD.UnboundedSyntax"]

[[lean_lib]]
name = "FIMADModels"

[[require]]
name = "YesMetaZFC"
git = "https://github.com/lanxinge/YesMetaZFC.git"
rev = "0e91389178caf34fc916ef40f76f84c3f3733714"
