name = "fiMadModels"
version = "0.1.0"
defaultTargets = ["FIMADModels"]

[[lean_lib]]
name = "Formalizations"
srcDir = ".."
roots = ["Formalizations.FIMAD.InternalSemantics", "Formalizations.FIMAD.SetTheorySentence", "Formalizations.FIMAD.CheckedZFC", "Formalizations.FIMAD.PosetRegular"]
globs = ["Formalizations.FIMAD.InternalSemantics", "Formalizations.FIMAD.SetTheorySentence", "Formalizations.FIMAD.CheckedZFC", "Formalizations.FIMAD.PosetRegular"]

[[lean_lib]]
name = "FIMADModels"

[[require]]
name = "YesMetaZFC"
git = "https://github.com/lanxinge/YesMetaZFC.git"
rev = "a4903d2054085db0b454363a5fb15f1a3e1f9eab"
